//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::content_entities::Entity as ContentEntities;
pub use super::contents::Entity as Contents;
pub use super::contents;
pub use super::content_entities;